name: My-Git-Actions
on:
  push:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  my-testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Print Hello
      - run: echo 'Hello World from Testing'
      
  my-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Print Hello
      - run: echo 'Hello World from deploy'
